name: API Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Generate HTML report
      run: npm run report

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-html-report
        path: cucumber_report.html
